@startuml
class MainSDLWindow {
-SDL_Window *window;
-SDL_Renderer *renderer;
MainSDLWindow(void)
~MainSDLWindow(void)
int Init(const char *title, int width, int height);
SDL_Renderer *GetRenderer(void);
}
@enduml